# Generated by Django 4.2.1 on 2023-05-24 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessLogic', '0002_student_lastname_alter_student_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
