# Generated by Django 4.2.1 on 2023-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessLogic', '0013_alter_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='@gmail.com', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
