# Generated by Django 4.2.1 on 2023-05-24 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessLogic', '0014_remove_student_dateofbirth_remove_student_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2003, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='N/A', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
